name: "spec"

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.3", "5.4"]

    runs-on: ubuntu-latest

    steps:
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz0b libharfbuzz-dev

    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: Install busted
      run: luarocks install busted

    - name: build
      run: luarocks make

    - name: test
      run: |
        busted --no-coverage -o utfTerminal
